### ISSUE TITLE
polymorphic associations

### ISSUE THREAD

**Issue by ahdinosaur** [fritzy/Dulcimer#19]
hi,

we want to create Models like so 

```
var Person = new dulcimer.Model({
  name: {},
  email: {},
}, { db: db, name: "person" });

var Circle = new dulcimer.Model({
  name: {},
  members: {
    foreignCollection: ["person", "circle"]
  },
}, { db: db, name: "circle"});
```

where a Circle has members of type Person or Circle.

is this possible with the current setup? we were thinking of having 'personMember' and 'circleMember' properties and using derive for a 'member' property, but then it gets complicated on saves and surely a better way could be possible. if it's not possible now, what can we do to help make it happen?

cheers!

**Comment by fritzy** [comment]
I'm officially deprecating the project and closing the issues. Thanks for your interest.
