### ISSUE TITLE
Bumped version to be able to use in node v0.11

### ISSUE THREAD

**Issue by ifraixedes** [fritzy/Dulcimer#24]
Hi,

I wanted to use this module with node v0.11, but the current release doesn't compile so it cannot be used on it.

Due that, I looked for the issues that npm install reported and I figured out that three dependencies don't compile on node v0.11, however two of them have been update to newer releases and they compile on node v0.11 and another one is able to compile on node v0.11 if a working progress branch is used.

Making those changes in the dependencies I have been able to install the module in node v0.11; although it is not stable and one of the dependencies doesn't have a official release which works on node v0.11, you may want to create a branch in this repo to give the chance to people who like to tinker in the bleeding-edge to use the module just pointing the module to an specific branch created for this aim.

You can take a look to the changes in my [fork](https://github.com/ifraixedes/Dulcimer/tree/node-v0.11) and create a branch with those or if you prefer create a branch from master and I will send a PR from my fork to that new branch.

By the way, the current test passes in the mentioned fork.

**Comment by edimoldovan** [comment]
Hi,

Dulcimer has a bignum dependency which has its latest version on 0.9.2. The one required by Dulcimer breaks npm install on node v0.12.

Eduard

**Comment by fritzy** [comment]
Should work now. Also tested in io.js 1.5.1

**Comment by edimoldovan** [comment]
Trying it right away!
